[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
temp = "GuN8f7tuKKaDQ3RjP91hSKEE1Xg6ADgYxecfEu8akt74"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/im/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
